server.port=8081
spring.application.name=delivery

spring.datasource.url=jdbc:derby:database;create=true
spring.datasource.username=derbyuser
spring.datasource.password=password
#preserva los datos entre ejecuciones, si se cambia a create se borran los datos previos
spring.jpa.hibernate.ddl-auto=update
#muestra en consola codigo SQL de forma indentada
spring.jackson.serialization.indent-output=true